-- INITIAL SCHEMA FOR TARTEEL TOTS (CFR REFACTOR)

-- 1. FAMILIES
CREATE TABLE IF NOT EXISTS families (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. PROFILES (PARENTS)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    family_id UUID REFERENCES families(id),
    email TEXT,
    role TEXT CHECK (role IN ('mother', 'father')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CHILDREN
CREATE TABLE IF NOT EXISTS children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id UUID REFERENCES families(id),
    name TEXT NOT NULL,
    age INT,
    avatar TEXT,
    daily_goal_minutes INT DEFAULT 15,
    memorization_baseline JSONB DEFAULT '{"current_surah": 1, "current_ayah": 1}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. PROGRESS (CFR LOGIC)
CREATE TABLE IF NOT EXISTS progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT REFERENCES children(id) ON DELETE CASCADE,
    surah INT NOT NULL,
    chunkId TEXT NOT NULL,
    level INT DEFAULT 1,
    lastReviewed TIMESTAMP WITH TIME ZONE,
    nextSuggested TIMESTAMP WITH TIME ZONE,
    lastGrade TEXT,
    favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. SESSIONS
CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT REFERENCES children(id) ON DELETE CASCADE,
    family_id UUID REFERENCES families(id),
    date DATE DEFAULT CURRENT_DATE,
    duration INT, -- total seconds
    mode TEXT, -- 'interactive', 'live_guide', 'radio'
    type TEXT, -- 'new', 'review', 'mixed'
    screen_time INT,
    audio_only_time INT,
    ayahs_reviewed INT DEFAULT 0,
    ayahs_new INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. GARDEN STATE (OPTIONAL PERSISTENCE)
CREATE TABLE IF NOT EXISTS garden_state (
    child_id BIGINT REFERENCES children(id) ON DELETE CASCADE PRIMARY KEY,
    streak INT DEFAULT 0,
    last_visit DATE,
    growth_stage INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) - BASIC
ALTER TABLE families ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE children ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

-- Simple policy: users can only see data tied to their family_id
-- (Requires profile to be set up first)
