-- Add grade attribution to track which parent gave each grade
-- This enables multi-parent grade history + conflict resolution

ALTER TABLE progress ADD COLUMN IF NOT EXISTS graded_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS grade_timestamp TIMESTAMP WITH TIME ZONE;

-- Create grade_history table for audit trail (all past grades, not just latest)
CREATE TABLE IF NOT EXISTS grade_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id BIGINT REFERENCES progress(id) ON DELETE CASCADE,
    child_id BIGINT REFERENCES children(id) ON DELETE CASCADE,
    family_id UUID REFERENCES families(id) ON DELETE CASCADE,
    surah INT NOT NULL,
    chunkId TEXT NOT NULL,
    grade TEXT NOT NULL CHECK (grade IN ('🔴', '🟡', '🟢')),
    graded_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    graded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_grade_history_progress ON grade_history(progress_id);
CREATE INDEX IF NOT EXISTS idx_grade_history_child ON grade_history(child_id);
CREATE INDEX IF NOT EXISTS idx_grade_history_family ON grade_history(family_id);
CREATE INDEX IF NOT EXISTS idx_grade_history_graded_by ON grade_history(graded_by);
CREATE INDEX IF NOT EXISTS idx_grade_history_graded_at ON grade_history(graded_at);

-- RLS for grade_history
ALTER TABLE grade_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view grade history for their family"
ON grade_history FOR SELECT
USING (family_id IN (SELECT family_id FROM memberships WHERE profile_id = auth.uid()));

CREATE POLICY "Users can insert grade history for their family"
ON grade_history FOR INSERT
WITH CHECK (family_id IN (SELECT family_id FROM memberships WHERE profile_id = auth.uid()));

-- Function to log grade changes to history before updating progress
CREATE OR REPLACE FUNCTION log_grade_to_history()
RETURNS TRIGGER AS $$
DECLARE
  child_family_id UUID;
BEGIN
  -- Get family_id from child
  SELECT family_id INTO child_family_id FROM children WHERE id = NEW.child_id;
  
  -- Insert into grade_history if grade changed
  IF (OLD.lastGrade IS DISTINCT FROM NEW.lastGrade) OR (OLD.lastGrade IS NULL) THEN
    INSERT INTO grade_history (
      progress_id, child_id, family_id, surah, chunkId, grade, graded_by, graded_at
    ) VALUES (
      NEW.id, NEW.child_id, child_family_id, NEW.surah, NEW.chunkId, NEW.lastGrade, NEW.graded_by, NOW()
    );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-log grade changes
CREATE TRIGGER progress_grade_change_trigger
AFTER UPDATE ON progress
FOR EACH ROW
WHEN (OLD.lastGrade IS DISTINCT FROM NEW.lastGrade)
EXECUTE FUNCTION log_grade_to_history();

-- Update progress table RLS to include graded_by visibility
CREATE POLICY "Users can view progress for their family children"
ON progress FOR SELECT
USING (child_id IN (
  SELECT id FROM children WHERE family_id IN (
    SELECT family_id FROM memberships WHERE profile_id = auth.uid()
  )
));

CREATE POLICY "Users can update progress for their family children"
ON progress FOR UPDATE
USING (child_id IN (
  SELECT id FROM children WHERE family_id IN (
    SELECT family_id FROM memberships WHERE profile_id = auth.uid()
  )
));
