-- Audit log for child profile changes
-- Tracks name, age, avatar changes + editor info

-- Add created_by and updated_by to children table
ALTER TABLE children ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE children ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS child_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id BIGINT REFERENCES children(id) ON DELETE CASCADE,
    family_id UUID REFERENCES families(id) ON DELETE CASCADE,
    changed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    field_name TEXT NOT NULL CHECK (field_name IN ('name', 'age', 'avatar', 'daily_goal_minutes', 'memorization_baseline')),
    old_value TEXT,
    new_value TEXT,
    change_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_child_audit_log_child ON child_audit_log(child_id);
CREATE INDEX IF NOT EXISTS idx_child_audit_log_family ON child_audit_log(family_id);
CREATE INDEX IF NOT EXISTS idx_child_audit_log_changed_by ON child_audit_log(changed_by);
CREATE INDEX IF NOT EXISTS idx_child_audit_log_created_at ON child_audit_log(created_at);

-- RLS for child_audit_log
ALTER TABLE child_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view audit log for their family children"
ON child_audit_log FOR SELECT
USING (family_id IN (SELECT family_id FROM memberships WHERE profile_id = auth.uid()));

CREATE POLICY "Users can insert audit log for their family"
ON child_audit_log FOR INSERT
WITH CHECK (family_id IN (SELECT family_id FROM memberships WHERE profile_id = auth.uid()));

-- Function to log child changes
CREATE OR REPLACE FUNCTION log_child_changes()
RETURNS TRIGGER AS $$
DECLARE
  tracked_fields TEXT[] := ARRAY['name', 'age', 'avatar', 'daily_goal_minutes'];
  field_name TEXT;
BEGIN
  FOREACH field_name IN ARRAY tracked_fields LOOP
    IF OLD IS NULL THEN
      -- Insert on create - log initial values
      CASE field_name
        WHEN 'name' THEN
          INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
          VALUES (NEW.id, NEW.family_id, NEW.created_by, field_name, NULL, NEW.name);
        WHEN 'age' THEN
          INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
          VALUES (NEW.id, NEW.family_id, NEW.created_by, field_name, NULL, NEW.age::text);
        WHEN 'avatar' THEN
          INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
          VALUES (NEW.id, NEW.family_id, NEW.created_by, field_name, NULL, NEW.avatar);
        WHEN 'daily_goal_minutes' THEN
          INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
          VALUES (NEW.id, NEW.family_id, NEW.created_by, field_name, NULL, NEW.daily_goal_minutes::text);
      END CASE;
    ELSE
      -- Update on change
      CASE field_name
        WHEN 'name' THEN
          IF OLD.name IS DISTINCT FROM NEW.name THEN
            INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
            VALUES (NEW.id, NEW.family_id, NEW.updated_by, field_name, OLD.name, NEW.name);
          END IF;
        WHEN 'age' THEN
          IF OLD.age IS DISTINCT FROM NEW.age THEN
            INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
            VALUES (NEW.id, NEW.family_id, NEW.updated_by, field_name, OLD.age::text, NEW.age::text);
          END IF;
        WHEN 'avatar' THEN
          IF OLD.avatar IS DISTINCT FROM NEW.avatar THEN
            INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
            VALUES (NEW.id, NEW.family_id, NEW.updated_by, field_name, OLD.avatar, NEW.avatar);
          END IF;
        WHEN 'daily_goal_minutes' THEN
          IF OLD.daily_goal_minutes IS DISTINCT FROM NEW.daily_goal_minutes THEN
            INSERT INTO child_audit_log (child_id, family_id, changed_by, field_name, old_value, new_value)
            VALUES (NEW.id, NEW.family_id, NEW.updated_by, field_name, OLD.daily_goal_minutes::text, NEW.daily_goal_minutes::text);
          END IF;
      END CASE;
    END IF;
  END LOOP;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-log child changes
CREATE TRIGGER child_changes_trigger
AFTER INSERT OR UPDATE ON children
FOR EACH ROW
EXECUTE FUNCTION log_child_changes();
